---
- name: Create adminer folder
  file: 
    path: "{{ web_folder }}"
    recurse: yes
    state: directory

- name: Get the file
  get_url:
    url: http://www.adminer.org/latest.php
    dest: "{{ web_folder }}/adminer.php"
    owner: "{{ webserver_user }}"
    group: "{{ webserver_user }}"
    mode: 0775